tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_padding_copy(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* scaling_factor);
tinyengine_status depthwise_kernel3x3_stride1_inplace_or(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* scaling_factor);
tinyengine_status depthwise_kernel3x3_stride2_inplace_or(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* scaling_factor);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_R(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_mean_2C(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, const q7_t* fold_weight);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_mean_2C_no_opt(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, const q7_t* fold_weight);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_fpreq_mask(q7_t *input, const uint16_t input_x, const uint16_t input_y,
            const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
            const float *scales,
            const int32_t output_offset, const int32_t input_offset,
            const int32_t output_activation_min,
            const int32_t output_activation_max, q7_t *output, q7_t *output_mask,
            const uint16_t output_x, const uint16_t output_y,
            const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_fpreq_bitmask(q7_t *input, const uint16_t input_x, const uint16_t input_y,
            const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
            const float *scales,
            const int32_t output_offset, const int32_t input_offset,
            const int32_t output_activation_min,
            const int32_t output_activation_max, q7_t *output, q7_t *output_mask,
            const uint16_t output_x, const uint16_t output_y,
            const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_padding_copy(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* scaling_factor);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_fpreq_mask(q7_t *input, const uint16_t input_x, const uint16_t input_y,
            const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
            const float *scales,
            const int32_t output_offset, const int32_t input_offset,
            const int32_t output_activation_min,
            const int32_t output_activation_max, q7_t *output, q7_t *output_mask,
            const uint16_t output_x, const uint16_t output_y,
            const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_fpreq_bitmask(q7_t *input, const uint16_t input_x, const uint16_t input_y,
            const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
            const float *scales,
            const int32_t output_offset, const int32_t input_offset,
            const int32_t output_activation_min,
            const int32_t output_activation_max, q7_t *output, q7_t *output_mask,
            const uint16_t output_x, const uint16_t output_y,
            const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_R(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, const q7_t* fold_weight);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_R_odd(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, const q7_t* fold_weight);
tinyengine_status depthwise_kernel7x7_stride1_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);

tinyengine_status depthwise_kernel5x5_stride1_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);

tinyengine_status depthwise_kernel7x7_stride2_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);

tinyengine_status depthwise_kernel5x5_stride2_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value);

tinyengine_status new_depthwise_kernel3x3_stride1_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* border_kernel);

tinyengine_status new_depthwise_kernel3x3_stride2_inplace_CHW(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value, q7_t* border_kernel);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_FStore(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t pad);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_RStore_FLoad(q7_t* input, const uint16_t input_x, const uint16_t input_y,
    const uint16_t input_ch, const q7_t* kernel, const int32_t* bias, const int32_t* biasR,
    const int32_t* output_shift, const int32_t* output_mult,
    const int32_t output_offset, const int32_t input_offset,
    const int32_t output_activation_min,
    const int32_t output_activation_max, q7_t* output,
    const uint16_t output_x, const uint16_t output_y,
    const uint16_t output_ch, q15_t* runtime_buf, q7_t pad_value,
    q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
    q7_t* r_store,
    q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
    q7_t pad);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_FStore_RLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t* r_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_BStore_RLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* b_store,
				q7_t* r_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_FStore_FLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_RStore_BLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store,
				q7_t* b_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_FStore_BLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t* b_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_BStore_FLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* b_store,
				q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_FLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_RStore_FLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store,
				q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_FStore(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_FStore_RLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t* r_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_BStore_RLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* b_store,
				q7_t* r_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_FStore_FLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store, q7_t* b_store, q7_t* br_store,
				q7_t* r_load_start, q7_t* b_load_start, q7_t* br_load_start,
				q7_t pad);

tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_RStore_BLoad(q7_t *input, const uint16_t input_x, const uint16_t input_y,
                const uint16_t input_ch, const q7_t *kernel, const int32_t *bias, const int32_t *biasR,
                const int32_t *output_shift, const int32_t *output_mult,
                const int32_t output_offset, const int32_t input_offset,
                const int32_t output_activation_min,
                const int32_t output_activation_max, q7_t *output,
                const uint16_t output_x, const uint16_t output_y,
                const uint16_t output_ch, q15_t *runtime_buf, q7_t pad_value,
				q7_t l_pad, q7_t r_pad, q7_t t_pad, q7_t b_pad,
				q7_t* r_store,
				q7_t* b_load_start,
				q7_t pad);
tinyengine_status depthwise_kernel3x3_stride1_inplace_CHW_PSK(q7_t* input, const uint16_t input_x, const uint16_t input_y,
    const uint16_t input_ch, const q7_t* kernel, const int32_t* bias, const int32_t* biasR,
    const int32_t* output_shift, const int32_t* output_mult,
    const int32_t output_offset, const int32_t input_offset,
    const int32_t output_activation_min,
    const int32_t output_activation_max, q7_t* output,
    const uint16_t output_x, const uint16_t output_y,
    const uint16_t output_ch, q15_t* runtime_buf, q7_t pad_value, const q7_t* fold_weight);
tinyengine_status depthwise_kernel3x3_stride2_inplace_CHW_PSK(q7_t* input, const uint16_t input_x, const uint16_t input_y,
    const uint16_t input_ch, const q7_t* kernel, const int32_t* bias, const int32_t* biasR,
    const int32_t* output_shift, const int32_t* output_mult,
    const int32_t output_offset, const int32_t input_offset,
    const int32_t output_activation_min,
    const int32_t output_activation_max, q7_t* output,
    const uint16_t output_x, const uint16_t output_y,
    const uint16_t output_ch, q15_t* runtime_buf, q7_t pad_value, const q7_t* fold_weight);
tinyengine_status convolve_s8_kernel3_inputch3_stride2_pad1_PSK(const q7_t* input, const uint16_t input_x, const uint16_t input_y,
    const uint16_t input_ch, const q7_t* kernel, const int32_t* bias,
    const int32_t* output_shift, const int32_t* output_mult,
    const int32_t output_offset, const int32_t input_offset,
    const int32_t output_activation_min,
    const int32_t output_activation_max, q7_t* output,
    const uint16_t output_x, const uint16_t output_y,
    const uint16_t output_ch, q15_t* runtime_buf, q15_t* kbuf, q7_t pad_value, const q7_t* fold_weight);